3 toggle states truthiness
ericpromislow/lirdle pull request #14
Opened 2023-03-02 13:49 UTC by jpalmerpivotal

Did not test locally...

2023-03-02 18:46 UTC, jpalmerpivotal commented
If there were to be a change to this PR I would suggest removing the comic sans from the neon blue color, as in hindsight, I suspect comic sans was intend to cast derision upon the lies.

2023-03-02 21:00 UTC, ericpromislow commented on build/view.js
> +            /* avoids assuming how users leverage the color highlighting
RIght. This was there because there can be only one lie on a line. But obviously the constraint doesn't hold for truths. So ok...

2023-03-02 21:02 UTC, ericpromislow commented on build/style.css
> +  font-family: "Comic Sans", "Comic Sans MS", "Apple Chancery", "Bradley Hand", "papyrus", serif;
Could you drop the Comic Sans fonts for perceived-truth? I like the way it bounces between comic-sans for lies and the fancier fonts for truths, leaving neutral at helvetica

2023-03-02 21:05 UTC, ericpromislow requested changes
Font change request, and could you just delete the commented-out code and leave a comment that users are expected to manage which squares are lies, so we're allowing two or more such squares in a line?

2023-03-02 23:29 UTC, jpalmerpivotal commented
Updated. Agreed on all accounts with the changes.
The comment is weird cause it explains why code isn't there... but it serves its purpose of explanation.

2023-03-03 02:32 UTC, ericpromislow approved these changes
LG - Thx! And we were def on the same page about truthfulness and comic-sans

2023-03-03 02:32 UTC, merged